- name: Install git
  package:
    name:
      - git
    state: latest


- name: Clone a Flaskex repo 
  git:
    repo: "{{ flaskex_repo }}" 
    dest: /home/ubuntu/Flaskex
    version: "{{ flaskex_branch }}"
    
